---
title: "Essential R Markdown Exercises for MATH513 Big Data and Social Network Visualization"
author: |
  | \textit{Lecturer}: Luciana Dalla Valle
  | \small \textit{Notes}: Julian Stander
  | \textit{Student}: Alex Mounsey (10570155)
date: "October 2020"
output:
  pdf_document:
    number_sections: true
---

# Exercise 1
Reproduce all the material that appears here using RMarkdown.

To save you typing, most of the text is given in the file 
TEXT_ONLY_of_Tutorial_8_R_Markdown.txt.

This material is meant to be instructive.

Please proceed step by step!

Check that your formatting works as you go along.

Your task is to:  
- Re-create this document

## Slides
It is possible to produce slides using RMarkdown. The following 
steps will get you started:

- Go to 'File', then
- 'New File', then
- 'R Markdown'...

Choose:

- Presentation
- Give the presentation a __Title__, such as _'First Presentation'_, 
and specify the __Author(s)__
- Specify __PDF (Beamer)__, then __OK__. Please note that this 
assumes that a __working version of LaTeX is installed__

RStudio should open an example R Markdown Beamer Presentation 
document:

- Run the document by clocking the __Knit__ or __Knit PDF__ button

Please make sure that you have saved the document to a suitable 
directory, with a sensible file name.

- Have a look at what is produced. You should see slides containing 
R code, together with the output that it produces, including a figure

__Warning__: There may be problems with creating slides  
You may have to keep pressing the __'Knit PDF'__ button, replying 
__'Install'__ (or similar) each time. This is because not all the 
underlying LaTeX packages have been properly installed. This is a 
nuisance, but only has to be done __once__ for each R session.

## Some Topics that We Will See in this Module
1. R Packages: Create and develop your R package as a collection 
of R functions and datasets
2. Social Media Sentiment Analysis: How to associate user sentiments 
to social media text data

## Statistical Tests
By the end of the module, we will have studied the following:

- Tests on the shape of a simple linear regression model
- Test on means:
  + Comparing two means: the _i_-test
  + Comparing more than two means: the analysis of variance 
  (__ANOVA__)

## The Analysis of Variance
Here is an example of initial analysis from:

Anderson, D, R., Sweeney, D. J., Williams, T. A., Freeman, J. 
and Shoesmith, E. (2010). Statistics for Business and Economics, 
Second Edition. South-Western CENGAGE Learning.

National Computer Products (NCP) manufactures printers at plants 
located in Ayr, Dusseldorf and Stockholm. To measure how much 
employees at these plants know about total quality management, a 
random sample of six employees was selected from each plant and 
given a quality awareness examination.

Here is one way to analyze this data:

- First, input the data into R:
```{R}
ayr <- c(85, 85, 82, 76, 71, 85)
dusseldorf <- c(71, 75, 73, 74, 69, 82)
stockholm <- c(59, 64, 62, 69, 75, 67)
```
- Put these vectors into a dataframe:
```{R}
df <- data.frame(ayr, dusseldorf, stockholm)
df
```

- Use functionality from `tidyr` to convert the dataframe to 
the long format so that all of the scores are in one column:
```{R, message = FALSE}
require(tidyr)

df_2 <- df %>%
  gather(Location, Score, 1:3)
df_2
```

- Use functionality from `dplyr` in order to turn 'Location' 
into a factor with suitable labels:
```{R, message = FALSE}
require(dplyr)

df_3 <- df_2 %>%
  mutate(Location_f = factor(Location,
                             levels = c("ayr", "dusseldorf", "stockholm"),
                             labels = c("Plant 1 Ayr",
                                        "Plant 2 Dusseldof",
                                        "Plant 3 Stockholm")))
df_3
```

- Now, compute the sample mean, the sample median, and the sample 
standard deviation score for each location:
```{R, message = FALSE}
df_3 %>%
  group_by(Location) %>%
  summarise(mean = mean(Score),
            median = median(Score),
            stdev = sd(Score))
```

The sample standard deviations (spread) are similar for each 
location, while the sample means and medians seem rather different. 
Let's examine this graphically:

- Visualize the data by means of boxplots using `ggplot2`:
```{R, message = FALSE}
require(ggplot2)

ggplot(df_3, aes(x = Location_f, y = Score, col = Location_f)) +
  geom_boxplot() +
  labs(x = "Location", y = "Examination Score", col = "Plant Location")
```

or, even:
```{R, message = FALSE}
ggplot(df_3, aes(x = Location_f, y = Score, fill = Location_f)) +
  geom_boxplot() +
  labs(x = "Location", y = "Examination Score", fill = "Plant Location")
```
These plots show considerable differences in the examination score 
between plant locations.

# The Analysis of Variance - Advanced
Here is, again, an example taken from:

Anderson, D, R., Sweeney, D. J., Williams, T. A., Freeman, J. 
and Shoesmith, E. (2010). Statistics for Business and Economics, 
Second Edition. South-Western CENGAGE Learning.

The examination scores for the 18 employees are listed in the 
following \LaTeX\ table:

| Plant 1 Ayr | Plant 2 Dusseldorf | Plant 3 Stockholm |
|:------:|:------:|:------:|
| 85 | 71 | 59 |
| 75 | 75 | 64 |
| 82 | 73 | 62 |
| 76 | 74 | 69 |
| 71 | 69 | 75 |
| 85 | 82 | 67 |

We can perform a test to see whether the _underlying_ mean examination 
scores for the three manufacturing plants are the same or not. 
We are __not__ asking whether the means of the six examination scores 
from each plant are different; we know this from summary statistics 
calculated elsewhere. We are asking a __more profound__ question: 
are the means of __all possible scores__ from the plants different?

First, let us write down the analysis of variance model:
\begin{eqnarray*}
  y_i & = & \mu_A + \epsilon_i \mbox{ for Plant 1 Ayr} \\
  y_i & = & \mu_D + \epsilon_i \mbox{ for Plant 2 Dusseldorf} \\
  y_i & = & \mu_S + \epsilon_i \mbox{ for Plant 3 Stocholm}
\end{eqnarray*}

In which the errors $\epsilon_i$ ~ $N(0,a^2$ independently

- To answer this question about the underlying means, we formulate 
two hypotheses.

The _null hypotheses_ is $H_0:\epsilon_A = \epsilon_D = \epsilon_S$, 
in which $\epsilon_A/\epsilon_D/\epsilon_S$ are the underlying mean 
scores from Plant 1 Ayr/Plant 2 Dusseldorf/Plant 3 Stockholm.

The _alternative_ hypothesis is $H_1$: underlying means are not 
all equal.

- We now perform an Analysis of Variance of __ANOVA__ test. __ANOVA__ 
is an example of a linear model.

First, we have to manipulate the data into a suitable format, as we 
have done before:

```{R message = FALSE}

require(tidyr)
require(dplyr)
df <- data.frame(ayr, dusseldorf, stockholm)
df_2 <- df %>% 
        gather(Location, Score,  1:3)
df_3 <- df_2 %>% mutate(Location_f = 
                        factor(Location, 
                         levels = c("ayr",
                                    "dusseldorf",
                                    "stockholm"),
                         labels = c("Plant 1 Ayr", 
                                    "Plant 2 Dusseldorf", 
                                    "Plant 3 Stockholm")))
df_3
```

Now, we perform the __ANOVA__ test, using the `lm` function:
```{R message=FALSE}
m <- lm(Score ~ Location_f, data = df_3)
anova(m)
```

We can extract the _p_-value:
```{R message = FALSE}
p_value <- anova(m)$"Pr(>F)"[1]
p_value
```

The _p_-value is `r p_value`. As this is less than 0.05, we 
reject the null hypothesis $H_0$ and conclude that there is a 
difference in the underlying mean examination scores from the 
three manufacturing plants.